sudo: required
services:
  - docker

before_install:
  - docker build -t sankarbv/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sankarbv/docker-react npm test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-921064647968"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"